### ISSUE TITLE
About ReactNative_Distance Repository

### ISSUE THREAD

**Issue by filmhomage** [filmhomage/ReactNative_Distance#1]
### Abstract
A small application to calculate the distance between two addresses entered by a user.

-----

### Development environment

- [x] XCode 8.3.3
- [x] iOS Simulator 10.3

-----

### Dependencies

```json
    "geolib": "^2.0.22",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.45.1",
    "react-native-geocoder": "^0.4.8",
    "react-addons-update": "^15.6.0"
```

----

### Package
- [x] [geolib](https://github.com/manuelbieh/Geolib)
- [x] [react-addons-update](https://facebook.github.io/react/docs/update.html)
- [x] [react-native-geocoder](https://github.com/devfd/react-native-geocoder)

----

### import 

- [x] import geolib from 'geolib';
- [x] import update from 'react-addons-update';
- [x] import Geocoder from 'react-native-geocoder';

----

### XCode Setting 

<img width="993" alt="geolib" src="https://user-images.githubusercontent.com/4126751/27180567-55e35dbe-51d4-11e7-86b7-af060a00104b.png">

-----

### SCREENSHOT
<img width="563" alt="screenshot" src="https://user-images.githubusercontent.com/4126751/27181919-d8f3d602-51d9-11e7-801a-c52183eeffef.png">

**Comment by filmhomage** [comment]
@notjosh 
Hi notjosh! This is Jonghyun Kim.
React Native Exercise! Please check this repository. 😁

**Comment by notjosh** [comment]
If I clone the repo, running `yarn install` gives me:

```
$ yarn install
yarn install v0.24.6
error Error parsing JSON at "/Users/joshua/dev/work/Taxfix/coding-exercises/filmhomage/ReactNative_Distance/package.json", "/Users/joshua/dev/work/Taxfix/coding-exercises/filmhomage/ReactNative_Distance/package.json: Unexpected token } in JSON at position 309".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by notjosh** [comment]
If I fix the JSON, and again run `yarn install` I get a diff of:

```diff
diff --git a/package.json b/package.json
index 0b81ea1..3f6f73e 100644
--- a/package.json
+++ b/package.json
@@ -9,7 +9,7 @@
   "dependencies": {
     "react": "16.0.0-alpha.12",
     "react-native": "0.45.1",
-    "react-native-geocoder": "^0.4.8",
+    "react-native-geocoder": "^0.4.8"
   },
   "devDependencies": {
     "babel-jest": "20.0.3",
diff --git a/yarn.lock b/yarn.lock
index f0e2676..b103c99 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -2994,6 +2994,10 @@ react-devtools-core@^2.1.8:
     shell-quote "^1.6.1"
     ws "^2.0.3"

+react-native-geocoder@^0.4.8:
+  version "0.4.8"
+  resolved "https://registry.yarnpkg.com/react-native-geocoder/-/react-native-geocoder-0.4.8.tgz#4763ad0a45bd365061b80f52c06564fcc62658e1"
+
 react-native@0.45.1:
   version "0.45.1"
   resolved "https://registry.yarnpkg.com/react-native/-/react-native-0.45.1.tgz#b3283c4a88233421f9c662a2ff1a4ccc8a9f07c0"
(END)
```

Is it possible you have a commit missing that hasn't been pushed?

**Comment by notjosh** [comment]
And then when I run the app, I get: 

```
Loading dependency graph, done.
error: bundling: UnableToResolveError: Unable to resolve module `geolib` from `/Users/joshua/dev/work/Taxfix/coding-exercises/filmhomage/ReactNative_Distance/SearchPage.js`: Module does not exist in the module map or in these directories:
  /Users/joshua/dev/work/Taxfix/coding-exercises/filmhomage/ReactNative_Distance/node_modules

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
    at UnableToResolveError (/Users/joshua/dev/work/Taxfix/coding-exercises/filmhomage/ReactNative_Distance/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:612:5)
    at ResolutionRequest._resolveNodeDependency (/Users/joshua/dev/work/Taxfix/coding-exercises/filmhomage/ReactNative_Distance/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:470:11)
    at tryResolveSync (/Users/joshua/dev/work/Taxfix/coding-exercises/filmhomage/ReactNative_Distance/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:130:20)
    at tryResolveSync (/Users/joshua/dev/work/Taxfix/coding-exercises/filmhomage/ReactNative_Distance/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:89:12)
    at ResolutionRequest.resolveDependency (/Users/joshua/dev/work/Taxfix/coding-exercises/filmhomage/ReactNative_Distance/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:128:22)
    at dependencyNames.map.name (/Users/joshua/dev/work/Taxfix/coding-exercises/filmhomage/ReactNative_Distance/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:142:59)
    at Array.map (native)
    at ResolutionRequest.resolveModuleDependencies (/Users/joshua/dev/work/Taxfix/coding-exercises/filmhomage/ReactNative_Distance/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:142:42)
    at module.readFresh.then (/Users/joshua/dev/work/Taxfix/coding-exercises/filmhomage/ReactNative_Distance/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:182:40)
    at process._tickCallback (internal/process/next_tick.js:103:7)
Bundling `index.ios.js`  99.5% (391/392), failed.
```

Seems like there are missing dependencies in `package.json`.

I'll halt my progress here for now. Can you try to resolve these issues and let me know when a fresh clone can run the app? Thanks!

**Comment by filmhomage** [comment]
@notjosh 
Thank you for your comment. Let you know after I will check again soon.

**Comment by filmhomage** [comment]
## About current error

### 【Terminal ; from clone and run-ios】

```
jonghyuns-mbp:02_ReactNative_recheck JonghyunKim$ git clone https://github.com/filmhomage/ReactNative_Distance.git
Cloning into 'ReactNative_Distance'...
remote: Counting objects: 98, done.
remote: Compressing objects: 100% (71/71), done.
remote: Total 98 (delta 17), reused 86 (delta 10), pack-reused 0
Unpacking objects: 100% (98/98), done.
jonghyuns-mbp:02_ReactNative_recheck JonghyunKim$ cd ReactNative_Distance/
jonghyuns-mbp:ReactNative_Distance JonghyunKim$ yarn install
yarn install v0.24.6
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 13.99s.
jonghyuns-mbp:ReactNative_Distance JonghyunKim$ react-native run-ios
Scanning 560 folders for symlinks in /Users/JonghyunKim/PROJECT/02_ReactNative_recheck/ReactNative_Distance/node_modules (4ms)
Found Xcode project ReactNative_Distance.xcodeproj
Launching iPhone 6 (iOS 10.3)...

.....

** BUILD SUCCEEDED **

The following commands produced analyzer issues:
	Analyze /Users/JonghyunKim/PROJECT/02_ReactNative_recheck/ReactNative_Distance/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c
	Analyze /Users/JonghyunKim/PROJECT/02_ReactNative_recheck/ReactNative_Distance/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c
(2 commands with analyzer issues)

Installing build/Build/Products/Debug-iphonesimulator/ReactNative_Distance.app
Launching org.reactjs.native.example.ReactNative-Distance
org.reactjs.native.example.ReactNative-Distance: 48834
```

------


### 【Terminal ; react-native run-ios】

```
Last login: Mon Jun 19 14:34:30 on ttys001
jonghyuns-mbp:~ JonghyunKim$ /Users/JonghyunKim/PROJECT/02_ReactNative_recheck/ReactNative_Distance/node_modules/react-native/packager/launchPackager.command ; exit;

~/PROJECT/02_ReactNative_recheck/ReactNative_Distance/node_modules/react-native/packager ~
Scanning 560 folders for symlinks in /Users/JonghyunKim/PROJECT/02_ReactNative_recheck/ReactNative_Distance/node_modules (6ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/JonghyunKim/PROJECT/02_ReactNative_recheck/ReactNative_Distance 


React packager ready.

Loading dependency graph, done.
Bundling `index.ios.js`  100.0(398/398), done.
Launching Dev Tools...
```

### 【Screenshot run-ios】

![run-ios screenshot](https://user-images.githubusercontent.com/4126751/27285827-3e805faa-54fe-11e7-9273-a1a2b653478b.png)

**Comment by filmhomage** [comment]
@notjosh 
I fixed the problem of ``` yarn install ``` and ``` dependencies in package.json ``` on #2.
Then I double checked from ``` clone this repository ``` to ``` run-ios ```.
Please check my repository again. Thank your for your time and comment!

**Comment by filmhomage** [comment]
@notjosh 
2 days ago, I had fixed install problem and dependencies. 
Please confirm again. Best regards 🙇🏻
